-- TABLE RECORDS CLEANUP
DELETE FROM TBL_BATCH_CONFIG;
DELETE FROM TBL_BATCH_BILLER_PAYMENT_CONFIG;
DELETE FROM vw_batch_tbl_biller;
DELETE FROM TBL_BILLER_CATEGORY;

-- TBL_BATCH_CONFIG
INSERT INTO TBL_BATCH_CONFIG(ID, PARAMETER_KEY, PARAMETER_VALUE, CREATED_TIME, CREATED_BY, UPDATED_TIME, UPDATED_BY)
VALUES(1, 'batch.system.date',  TO_CHAR(NOW(), 'yyyy-MM-dd'), NOW(), 'TESTER', NOW(), 'TESTER');

INSERT INTO TBL_BATCH_CONFIG(ID, PARAMETER_KEY, PARAMETER_VALUE, CREATED_TIME, CREATED_BY, UPDATED_TIME, UPDATED_BY)
VALUES(2, 'ibg.reject.last.processed.success.job.execution.id', '0', NOW(), 'TESTER', NOW(), 'TESTER');

INSERT INTO TBL_BO_CONFIG_GENERIC (CONFIG_TYPE, CONFIG_CODE, CONFIG_DESC, CREATED_TIME, CREATED_BY, UPDATED_TIME, UPDATED_BY) 
VALUES ('user_security', 'days_to_inactive_user', '30', NOW(), 'Admin', NOW(), 'ADMIN');

INSERT INTO TBL_BO_CONFIG_GENERIC (CONFIG_TYPE, CONFIG_CODE, CONFIG_DESC, CREATED_TIME, CREATED_BY, UPDATED_TIME, UPDATED_BY) 
VALUES ('user_security', 'days_to_delete_user', '90', NOW(), 'Admin', NOW(), 'ADMIN');

-- TBL_BATCH_BILLER_PAYMENT_CONFIG
INSERT INTO TBL_BATCH_BILLER_PAYMENT_CONFIG(ID, BILLER_CODE, TEMPLATE_NAME, IBK_FTP_FOLDER, FTP_FOLDER, FILE_NAME_FORMAT, REPORT_UNIT_URI, STATUS, IS_REQUIRED_TO_EXECUTE, CREATED_TIME, CREATED_BY, UPDATED_TIME, UPDATED_BY, PROCESSED_BY)
VALUES(1, '5017', 'Standard_01', 'bpf_from_5017/', 'dcp_bpf_5017_Maxis_from', '5017${yyyyMMdd}.txt', 'test','A', '0', NOW(), 'TESTER', NOW(), 'TESTER', 'LDCPD9001F');

INSERT INTO TBL_BATCH_BILLER_PAYMENT_CONFIG(ID, BILLER_CODE, TEMPLATE_NAME, IBK_FTP_FOLDER, FTP_FOLDER, FILE_NAME_FORMAT, REPORT_UNIT_URI, STATUS, IS_REQUIRED_TO_EXECUTE, CREATED_TIME, CREATED_BY, UPDATED_TIME, UPDATED_BY, PROCESSED_BY)
VALUES(2, '5022', 'Standard_01', 'bpf_from_5022/', 'dcp_bpf_5022_IndahWater_from', '5012${yyyyMMdd}.txt', 'test','A', '0', NOW(), 'TESTER', NOW(), 'TESTER', 'LDCPD9001F');

INSERT INTO TBL_BATCH_BILLER_PAYMENT_CONFIG(ID, BILLER_CODE, TEMPLATE_NAME, IBK_FTP_FOLDER, FTP_FOLDER, FILE_NAME_FORMAT, REPORT_UNIT_URI, STATUS, IS_REQUIRED_TO_EXECUTE, CREATED_TIME, CREATED_BY, UPDATED_TIME, UPDATED_BY, PROCESSED_BY)
VALUES(3, '5085', 'Standard_01', 'bpf_from_5085/', 'dcp_bpf_5085_Ptptn_from', '5085${yyyyMMdd}.txt', 'test','A', '0', NOW(), 'TESTER', NOW(), 'TESTER', 'LDCPD9001F');

INSERT INTO TBL_BATCH_BILLER_PAYMENT_CONFIG(ID, BILLER_CODE, TEMPLATE_NAME, IBK_FTP_FOLDER, FTP_FOLDER, FILE_NAME_FORMAT, REPORT_UNIT_URI, STATUS, IS_REQUIRED_TO_EXECUTE, CREATED_TIME, CREATED_BY, UPDATED_TIME, UPDATED_BY, PROCESSED_BY)
VALUES(4, '5185', 'Standard_01', 'bpf_from_5185/', 'dcp_bpf_5185_umobile_from', '5185${yyyyMMdd}.txt', 'test','A', '0', NOW(), 'TESTER', NOW(), 'TESTER', 'LDCPD9001F');

INSERT INTO TBL_BATCH_BILLER_PAYMENT_CONFIG(ID, BILLER_CODE, TEMPLATE_NAME, IBK_FTP_FOLDER, FTP_FOLDER, FILE_NAME_FORMAT, REPORT_UNIT_URI, STATUS, IS_REQUIRED_TO_EXECUTE, CREATED_TIME, CREATED_BY, UPDATED_TIME, UPDATED_BY, PROCESSED_BY)
VALUES(5, '5167', 'Standard_01', 'bpf_from_5167/', 'dcp_bpf_5167_Mara_from', '5167${yyyyMMdd}.txt', 'test', 'A','0', NOW(), 'TESTER', NOW(), 'TESTER', 'LDCPD9001F');

-- vw_batch_tbl_biller
INSERT INTO vw_batch_tbl_biller(biller_collection_account_no, biller_code, biller_name, status, updated_time, category_id)
VALUES('21263900000117', '5017', 'Maxis', 'INACTIVE', DATE_SUB(NOW(), INTERVAL 2 DAY), 5);

INSERT INTO vw_batch_tbl_biller(biller_collection_account_no, biller_code, biller_name, status, updated_time, category_id)
VALUES('21263900000117', '5022', 'Indah Water Konsortium Sdn Bhd', 'DELETED', DATE_SUB(NOW(), INTERVAL 2 DAY), 84);

INSERT INTO vw_batch_tbl_biller(biller_collection_account_no, biller_code, biller_name, status, updated_time, category_id)
VALUES('21263900000117', '5085', 'Perbadanan Tabung Pendidikan Tinggi Nasional', 'ACTIVE', NOW(), 8);

INSERT INTO vw_batch_tbl_biller(biller_collection_account_no, biller_code, biller_name, status, updated_time, category_id)
VALUES('21263900000117', '5185', 'U Mobile Sdn Bhd', 'ACTIVE', NOW(), 5);

INSERT INTO vw_batch_tbl_biller(biller_collection_account_no, biller_code, biller_name, status, updated_time, category_id)
VALUES('21263900000117', '5167', 'Majlis Amanah Rakyat (MARA)', 'DELETED', DATE_SUB(NOW(), INTERVAL 1 DAY), 6);

-- TBL_BILLER_CATEGORY
INSERT INTO TBL_BILLER_CATEGORY(ID, CATEGORY_NAME, STATUS, CREATED_TIME, CREATED_BY, UPDATED_TIME, UPDATED_BY, SORT_ORDER)
VALUES('4', 'Utilities', 'ACTIVE', NOW(), 'ADMIN', NOW(), 'ADMIN', 0);

INSERT INTO TBL_BILLER_CATEGORY(ID, CATEGORY_NAME, STATUS, CREATED_TIME, CREATED_BY, UPDATED_TIME, UPDATED_BY, SORT_ORDER)
VALUES('5', 'Telcos', 'ACTIVE', NOW(), 'ADMIN', NOW(), 'ADMIN', 1);

INSERT INTO TBL_BILLER_CATEGORY(ID, CATEGORY_NAME, STATUS, CREATED_TIME, CREATED_BY, UPDATED_TIME, UPDATED_BY, SORT_ORDER)
VALUES('6', 'Govt. Bodies', 'ACTIVE', NOW(), 'ADMIN', NOW(), 'ADMIN', 2);

INSERT INTO TBL_BILLER_CATEGORY(ID, CATEGORY_NAME, STATUS, CREATED_TIME, CREATED_BY, UPDATED_TIME, UPDATED_BY, SORT_ORDER)
VALUES('7', 'Insurance', 'ACTIVE', NOW(), 'ADMIN', NOW(), 'ADMIN', 3);

INSERT INTO TBL_BILLER_CATEGORY(ID, CATEGORY_NAME, STATUS, CREATED_TIME, CREATED_BY, UPDATED_TIME, UPDATED_BY, SORT_ORDER)
VALUES('8', 'Others', 'ACTIVE', NOW(), 'ADMIN', NOW(), 'ADMIN', null);
