spring:
  profiles: uat
  datasource:
    dcpbo:
      jndi-name: java:/DCPBO
    dcp:
      jndi-name: java:/dcp

server:
  port: 8480

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://172.30.79.33:8480/registry/eureka}

logging:
  config: classpath:log4j2-uat.xml

dcp:
  stardate:
      url: http://172.30.79.33:8480/dcp-stardate-service/reference-id