spring:
  profiles: sit
  datasource:
    dcpbo:
      jndi-name: java:/DCPBO
    dcp:
      jndi-name: java:/dcp

server:
  port: 8380

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://172.30.79.32:8380/registry/eureka}

logging:
  config: classpath:log4j2-sit.xml

dcp:
  stardate:
    url: http://172.30.79.32:8380/dcp-stardate-service/reference-id