spring:
  profiles: uat_pilot
  datasource:
    dcpbo:
      jndi-name: java:/DCPBO
    dcp:
      jndi-name: java:/dcp
server:
  port: 8180

ldap:
  url: ldaps://172.30.81.104:636
  basedn: CN=Users,DC=bgiuatdom,DC=ent,DC=intranet,DC=rhbgroup,DC=com
  userdn: CN=dcpbo1,CN=Users,DC=bgiuatdom,DC=ent,DC=intranet,DC=rhbgroup,dc=com
  password: ENC(hT1pO+LEmHRiKSDOHB14Y6H9ebwF/Fj1)
  referral: follow
  nameField: displayName
  emailField: mail

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://172.30.79.34:8180/registry/eureka}

logging:
  config: classpath:log4j2.xml
