logging:
  file: bo-system-mgmt-service.log
  path: ${user.dir}/logs

spring:
  jms:
    jndi-name: java:jboss/exported/jms/DcpJmsConnectionFactory

auditLogger:
  audit:
    queue:
      name: java:jboss/exported/jms/queue/q_dcp_audit

eBean:
  config:
    name: db
    jndi:
      name: java:/dcp