spring:
  profiles: prod_02
  datasource:
    dcpbo:
      jndi-name: java:/DCPBO
    dcp:
      jndi-name: java:/dcp
server:
  port: 29443

ldap:
  url: ldaps://epdc07.portaldom.ent.intranet.rhbbank.com:636
  basedn: DC=portaldom,DC=ent,DC=intranet,DC=rhbbank,DC=com
  userdn: dcpbo2@portaldom.ent.intranet.rhbbank.com
  password: ENC(hT1pO+LEmHRiKSDOHB14Y6H9ebwF/Fj1)
  referral: follow
  nameField: displayName
  emailField: mail

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://myrhbodcpap02vp:29443/registry/eureka}

logging:
  config: classpath:log4j2.xml