spring:
  profiles: drl1_05
  datasource:
    jndi-name: java:/dcp
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver


server:
  port: 29443

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://myrhbodcpap05vp:29443/registry/eureka}

logging:
  config: classpath:log4j2.xml

dcp:
  stardate:
    url: http://myrhbodcpap05vp:29443/dcp-stardate-service/reference-id