CREATE TABLE dbo.DCP_AUDIT
(
	ID INT IDENTITY(1,1) NOT NULL,
	EVENT_CODE VARCHAR(5) NOT NULL,
	USER_ID INT NOT NULL,
	UPDATED_BY VARCHAR(40) NOT NULL,
	USERNAME VARCHAR(20) NOT NULL,
	CIS_NO VARCHAR(14),
	DEVICE_ID VARCHAR(40),
	STATUS_CODE VARCHAR(50),
	STATUS_DESCRIPTION VARCHAR(200),
	CHANNEL VARCHAR(20) NOT NULL,
	IP_ADDRESS VARCHAR(50) NOT NULL,
	TIMESTAMP DATETIME NOT NULL,
	CONSTRAINT PK_DCP_AUDIT PRIMARY KEY (ID)
);

CREATE TABLE dbo.DCP_AUDIT_CATEGORY_CONFIG
(
	ID INT NOT NULL,
	CATEGORY_NAME VARCHAR(50) NOT NULL,
	CONSTRAINT PK_DCP_AUDIT_CATEGORY_CONFIG PRIMARY KEY (ID)
);

CREATE TABLE dbo.DCP_AUDIT_EVENT_CONFIG
(
	ID INT NOT NULL,
	EVENT_CODE VARCHAR(5) NOT NULL,
	EVENT_NAME VARCHAR(80) NOT NULL,
	EVENT_CATEGORY_ID INT NOT NULL,
	DETAILS_TABLE_NAME VARCHAR(80) NOT NULL,
	CONSTRAINT PK_DCP_AUDIT_EVENT_CONFIG PRIMARY KEY (ID),
	CONSTRAINT FK_DCP_AUDIT_EVENT_CONFIG_EVENT_CATEGORY_ID FOREIGN KEY (EVENT_CATEGORY_ID) REFERENCES DCP_AUDIT_CATEGORY_CONFIG(ID)
);

CREATE TABLE dbo.DCP_AUDIT_BILL_PAYMENT
(
	ID INT IDENTITY(1,1) NOT NULL,
	AUDIT_ID INT NOT NULL,
	DETAILS NVARCHAR(4000) NOT NULL,
	CONSTRAINT PK_DCP_AUDIT_BILL_PAYMENT PRIMARY KEY (ID),
	CONSTRAINT FK_DCP_AUDIT_BILL_PAYMENT_AUDIT_ID FOREIGN KEY (AUDIT_ID) REFERENCES DCP_AUDIT(ID)
);

CREATE TABLE dbo.DCP_AUDIT_FUND_TRANSFER
(
	ID INT IDENTITY(1,1) NOT NULL,
	AUDIT_ID INT NOT NULL,
	DETAILS NVARCHAR(4000) NOT NULL,
	CONSTRAINT PK_DCP_AUDIT_FUND_TRANSFER PRIMARY KEY (ID),
	CONSTRAINT FK_DCP_AUDIT_FUND_TRANSFER_AUDIT_ID FOREIGN KEY (AUDIT_ID) REFERENCES DCP_AUDIT(ID)
);

CREATE TABLE dbo.DCP_AUDIT_MISC
(
	ID INT IDENTITY(1,1) NOT NULL,
	AUDIT_ID INT NOT NULL,
	DETAILS NVARCHAR(4000) NOT NULL,
	CONSTRAINT PK_DCP_AUDIT_MISC PRIMARY KEY (ID),
	CONSTRAINT FK_DCP_AUDIT_MISC_AUDIT_ID FOREIGN KEY (AUDIT_ID) REFERENCES DCP_AUDIT(ID)
);

CREATE TABLE dbo.DCP_AUDIT_PROFILE
(
	ID INT IDENTITY(1,1) NOT NULL,
	AUDIT_ID INT NOT NULL,
	DETAILS NVARCHAR(4000) NOT NULL,
	CONSTRAINT PK_DCP_AUDIT_PROFILE PRIMARY KEY (ID),
	CONSTRAINT FK_DCP_AUDIT_PROFILE_AUDIT_ID FOREIGN KEY (AUDIT_ID) REFERENCES DCP_AUDIT(ID)
);

CREATE TABLE dbo.DCP_AUDIT_TOPUP
(
	ID INT IDENTITY(1,1) NOT NULL,
	AUDIT_ID INT NOT NULL,
	DETAILS NVARCHAR(4000) NOT NULL,
	CONSTRAINT PK_DCP_AUDIT_TOPUP PRIMARY KEY (ID),
	CONSTRAINT FK_DCP_AUDIT_TOPUP_AUDIT_ID FOREIGN KEY (AUDIT_ID) REFERENCES DCP_AUDIT(ID)
);
