spring:
  profiles: dev
  datasource:
    dcpbo:
      jndi-name: java:/DCPBO
    dcp:
      jndi-name: java:/dcp
server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://172.30.79.45:8080/registry/eureka}

logging:
  config: classpath:log4j2-dev.xml

dcp:
  stardate:
    url: http://172.30.79.45:8080/dcp-stardate-service/reference-id

