#!/bin/bash
#
#  DIB BO Batch Spring Batch Launcher
#
#  Jobname : ASNBSplitJob
#  JobID   : LDCPD1006F
#  ReportName   : Daily ASNB Job
#  ReportID     : DMBID100
#
###########################################################
JOB_ID="LDCPD1006F"
JOB_NAME="ASNBSplitJob"
JOB_BEAN_NAME="ASNBSplitJob"
REPORT_ID="DMBID100"
OFFSET_DAY="0"
JOB_PARAMS="jobname=${JOB_BEAN_NAME} reportid=${REPORT_ID} batchid=${JOB_ID} offsetday=${OFFSET_DAY}"
BIN_ARGS="-Djasypt.encryptor.password=${MASTER_KEY}"
BIN_FILE=dcp-bo-dib-splitter.jar
###########################################################
BIN_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
HOME_DIR=$(dirname $BIN_DIR)

RUN_ID=$(date +"%Y%m%d_%H%M%S_%3N")
echo "[${JOB_ID}] Start timestamp : `date +"%Y-%m-%d %H:%M:%S"`" >> ${HOME_DIR}/log/${JOB_NAME}/${JOB_ID}_${RUN_ID}.log

# Create log folder if not exists
if [ ! -d "${HOME_DIR}/log/${JOB_NAME}" ]; then
  mkdir -p ${HOME_DIR}/log/${JOB_NAME}
fi

#Log start process for Zena and calculate duration
SECONDS=0
echo "================================================================================" >> ${HOME_DIR}/log/${JOB_ID}.log
echo "Job Name:	LDCPD1006F (ASNBSplitJob)" >> ${HOME_DIR}/log/${JOB_ID}.log
echo "--------------------------------------------------------------------------------" >> ${HOME_DIR}/log/${JOB_ID}.log
echo "Start Date:	`date +"%d-%m-%Y"`" >> ${HOME_DIR}/log/${JOB_ID}.log
echo "Start Time:	`date +"%H:%M:%S"`" >> ${HOME_DIR}/log/${JOB_ID}.log
echo "" >> ${HOME_DIR}/log/${JOB_ID}.log
echo "-------------------------------- RUN DATE START --------------------------------" >> ${HOME_DIR}/log/${JOB_ID}.log
echo "The run date is `date +"%Y%m%d"`" >> ${HOME_DIR}/log/${JOB_ID}.log
echo "-------------------------------- RUN DATE   END --------------------------------" >> ${HOME_DIR}/log/${JOB_ID}.log
echo "" >> ${HOME_DIR}/log/${JOB_ID}.log
echo "PROCESS" >> ${HOME_DIR}/log/${JOB_ID}.log
echo "--------------------------------      START     --------------------------------" >> ${HOME_DIR}/log/${JOB_ID}.log
echo "[`date +"%Y-%m-%d %H:%M:%S"`]	Proceeding to step 'splitDIBfileProcess'...." >> ${HOME_DIR}/log/${JOB_ID}.log
echo "--------------------------------       END      --------------------------------" >> ${HOME_DIR}/log/${JOB_ID}.log
echo "" >> ${HOME_DIR}/log/${JOB_ID}.log

#Run the job
$JAVA_HOME/bin/java -Dspring.config.location=${HOME_DIR}/config/bo-dib-splitter/ -jar ${BIN_ARGS} ${HOME_DIR}/app/${BIN_FILE} ${JOB_PARAMS} >> ${HOME_DIR}/log/${JOB_NAME}/${JOB_ID}_${RUN_ID}.log 2>&1

JOB_RET=$?
echo "[${JOB_ID}] End timestamp : `date +"%Y-%m-%d %H:%M:%S"`" >> ${HOME_DIR}/log/${JOB_NAME}/${JOB_ID}_${RUN_ID}.log
echo "[${JOB_ID}] Return code : $JOB_RET" >> ${HOME_DIR}/log/${JOB_NAME}/${JOB_ID}_${RUN_ID}.log

#Log end process for Zena and calculate duration
echo "STATUS" >> ${HOME_DIR}/log/${JOB_ID}.log
echo "--------------------------------------------------------------------------------" >> ${HOME_DIR}/log/${JOB_ID}.log
if [ "$JOB_RET" == 0 ]; then
echo "Batch job LDCPD1006F (ASNBSplitJob) COMPLETED" >> ${HOME_DIR}/log/${JOB_ID}.log
else
echo "Batch job LDCPD1006F (ASNBSplitJob) FAILED" >> ${HOME_DIR}/log/${JOB_ID}.log
echo "ERROR:	File not found!" >> ${HOME_DIR}/log/${JOB_ID}.log
fi
echo "" >> ${HOME_DIR}/log/${JOB_ID}.log
echo "End Date:		`date +"%d-%m-%Y"`" >> ${HOME_DIR}/log/${JOB_ID}.log
echo "End Time:		`date +"%H:%M:%S"`" >> ${HOME_DIR}/log/${JOB_ID}.log

duration=$SECONDS
echo "Duration:		$duration seconds" >> ${HOME_DIR}/log/${JOB_ID}.log
echo "================================================================================" >> ${HOME_DIR}/log/${JOB_ID}.log

exit $JOB_RET
